
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/liushuang?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf-8
    password: root
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      filters: stat,wall
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  mapper-locations: classpath*:Mappers/*Mapper.xml
  type-aliases-package: com.cqupt513.doubleliu.pojo
server:
  port: 8081
